platform :ios, '9.0'
inhibit_all_warnings!

use_frameworks!

target 'KZTableViewDataSource_Example' do
  pod 'KZTableViewDataSource', :path => '../'
end

post_install do |installer|
    # 解决Pod swift Version
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.2'
        end
    end
    
    # 解决警告 product cannot link framework Foundation.framework
    podsTargets = installer.pods_project.targets.find_all { |target| target.name.start_with?('Pods') }
    podsTargets.each do |target|
        target.frameworks_build_phase.clear
    end
end
